// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface IRCChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.IRCChannel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channel = 1;</code>
   */
  java.lang.String getChannel();
  /**
   * <code>optional string channel = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelBytes();
}
