// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface MembershipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.Membership)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channelname = 1;</code>
   */
  java.lang.String getChannelname();
  /**
   * <code>optional string channelname = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelnameBytes();

  /**
   * <code>optional string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
