// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface BooleanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.Boolean)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool value = 1;</code>
   */
  boolean getValue();
}
