// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface ChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.Chat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>optional string channelname = 2;</code>
   */
  java.lang.String getChannelname();
  /**
   * <code>optional string channelname = 2;</code>
   */
  com.google.protobuf.ByteString
      getChannelnameBytes();

  /**
   * <code>optional string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
