// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public final class IRCProto {
  private IRCProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_IRCUser_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_IRCUser_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_IRCChannel_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_IRCChannel_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_IRCResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_IRCResponse_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_Membership_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_Membership_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_Chat_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_Chat_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_irc_Boolean_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_irc_Boolean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/irc.proto\022\003irc\"\033\n\007IRCUser\022\020\n\010use" +
      "rname\030\001 \001(\t\"\035\n\nIRCChannel\022\017\n\007channel\030\001 \001" +
      "(\t\"\037\n\013IRCResponse\022\020\n\010response\030\001 \001(\t\"3\n\nM" +
      "embership\022\023\n\013channelname\030\001 \001(\t\022\020\n\010userna" +
      "me\030\002 \001(\t\";\n\004Chat\022\014\n\004text\030\001 \001(\t\022\023\n\013channe" +
      "lname\030\002 \001(\t\022\020\n\010username\030\003 \001(\t\"\030\n\007Boolean" +
      "\022\r\n\005value\030\001 \001(\0102\205\003\n\nIRCService\022,\n\010nickna" +
      "me\022\014.irc.IRCUser\032\020.irc.IRCResponse\"\000\022+\n\004" +
      "join\022\017.irc.Membership\032\020.irc.IRCResponse\"" +
      "\000\022,\n\005leave\022\017.irc.Membership\032\020.irc.IRCRes",
      "ponse\"\000\022(\n\004exit\022\014.irc.IRCUser\032\020.irc.IRCR" +
      "esponse\"\000\022,\n\013sendMessage\022\t.irc.Chat\032\020.ir" +
      "c.IRCResponse\"\000\022/\n\016receiveMessage\022\t.irc." +
      "Chat\032\020.irc.IRCResponse\"\000\022/\n\014checkChannel" +
      "\022\017.irc.IRCChannel\032\014.irc.Boolean\"\000\0224\n\rcre" +
      "ateChannel\022\017.irc.IRCChannel\032\020.irc.IRCRes" +
      "ponse\"\000B\026\n\010grpc.ircB\010IRCProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_irc_IRCUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irc_IRCUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_IRCUser_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_irc_IRCChannel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_irc_IRCChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_IRCChannel_descriptor,
        new java.lang.String[] { "Channel", });
    internal_static_irc_IRCResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_irc_IRCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_IRCResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_irc_Membership_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_irc_Membership_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_Membership_descriptor,
        new java.lang.String[] { "Channelname", "Username", });
    internal_static_irc_Chat_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_irc_Chat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_Chat_descriptor,
        new java.lang.String[] { "Text", "Channelname", "Username", });
    internal_static_irc_Boolean_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_irc_Boolean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_irc_Boolean_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
