// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface IRCResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.IRCResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>optional string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
