// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/irc.proto

package grpc.irc;

public interface IRCUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:irc.IRCUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
